WITH NUMBERS(N) AS
(
    SELECT 2
    FROM SYSIBM.SYSDUMMY1

    UNION ALL

    SELECT N + 1
    FROM NUMBERS
    WHERE N < 1000
)
SELECT LISTAGG(RTRIM(CHAR(N)), '&')
       WITHIN GROUP (ORDER BY N)
FROM NUMBERS N1
WHERE NOT EXISTS
(
    SELECT 1
    FROM NUMBERS N2
    WHERE N2.N > 1
      AND N2.N < N1.N
      AND MOD(N1.N, N2.N) = 0
);
